# Generated by Django 5.2.8 on 2025-12-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilmenor',
            old_name='usuario_principal_id',
            new_name='usuario_principal',
        ),
    ]
