# Generated by Django 5.2.8 on 2025-12-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menor', '0002_rename_usuario_principal_id_perfilmenor_usuario_principal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicioncrecimiento',
            old_name='id_perfil',
            new_name='perfil',
        ),
    ]
