# Generated by Django 5.2.8 on 2025-12-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menor', '0003_rename_id_perfil_medicioncrecimiento_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicioncrecimiento',
            name='edad_anos',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='medicioncrecimiento',
            name='edad_meses',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='medicioncrecimiento',
            name='imc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicioncrecimiento',
            name='perimetro_cefalico',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicioncrecimiento',
            name='perimetro_cintura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicioncrecimiento',
            name='peso',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='medicioncrecimiento',
            name='talla',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='medicioncrecimiento',
            name='fecha_medicion',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='medicioncrecimiento',
            name='observaciones_medicas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
