# Generated by Django 5.2.8 on 2025-12-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menor', '0004_medicioncrecimiento_edad_anos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicioncrecimiento',
            name='talla',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
