# Generated by Django 5.2.8 on 2025-12-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menor', '0005_alter_medicioncrecimiento_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilmenor',
            name='observaciones',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
