# Generated by Django 5.2.8 on 2025-12-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menor', '0006_alter_perfilmenor_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallaEdadNinasNac5AnosZscores',
            fields=[
                ('anos_meses', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('meses', models.IntegerField(blank=True, null=True)),
                ('menos2de', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('menos1de', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('mediana', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('mas1de', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('mas2de', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'talla_edad_ninas_nac5anos_zscores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TallaEdadNinosNac5AnosZscores',
            fields=[
                ('anos_meses', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('meses', models.IntegerField(blank=True, null=True)),
                ('menos2de', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('menos1de', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('mediana', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('mas1de', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('mas2de', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'talla_edad_ninos_nac5anos_zscores',
                'managed': False,
            },
        ),
    ]
